import ComponentB from 'component-b'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <p>Hello</p>
        <ComponentB />
      </main>
    </div>
  )
}
